[package]
name    = "telegraph-scoring"
version = "2.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = []
real_weights = []

[dependencies]
dlmalloc = { version = "0.2", features = ["global"] }
libm     = { version = "0.2", default-features = false }

[profile.release]
opt-level     = "z"
lto           = true
codegen-units = 1
panic         = "abort"
strip         = true
